### ISSUE TITLE
Transfer this package to Meteor Community Packages?

### ISSUE THREAD

**Issue by jankapunkt** [johanbrook/meteor-publication-collector#41]
Hi @johanbrook 

we are [Meteor Community Packages}(https://github.com/Meteor-Community-Packages) and are on the mission to keep Meteor packages maintained.

With the arrival of Meteor 3.0 we have some breaking changes in the ecosystem and would like to keep as many packages as possible compliant to avoid abandonware and security issues where possible.

Your package seems to be abandoned(?) and we would like to ask you kindly, if you could imagine to transfer your repository to our org.

Best
Jan

**Comment by johanbrook** [comment]
Sure, @jankapunkt, that would be neat. Maybe add me as past maintainer in the [README](https://github.com/johanbrook/meteor-publication-collector/blob/master/README.md) if you'd be so kind.

I'll transfer the repo now.

**Comment by jankapunkt** [comment]
@johanbrook did you [transfer as according to the docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account)? If so, we might add you to the org first. // cc @storytellercz

**Comment by johanbrook** [comment]
@jankapunkt Yep. But since it'll create a new repo in your org, I lack the permissions to do so when transferring.

**Comment by StorytellerCZ** [comment]
That should not be the case. In the settings there should be a transfer option that you can use without needing to create a new repository.

**Comment by johanbrook** [comment]
Sure, but implicitly a new repo will be created on your side when transferring, right? And my account isn’t permitted to do so.

**Comment by johanbrook** [comment]
Done.

**Comment by jankapunkt** [comment]
Hey @johanbrook thanks a lot for the transfer! I finally managed to make it 3.0-ready but I can't publish it. There is one last step so we can publish new releases. You need to add `communitypackages` as valid publisher for the package.
@StorytellerCZ do you remember how this is done?

**Comment by jankapunkt** [comment]
@StorytellerCZ as this is still an issue I would go to publish under `communitypackages:publication-collector` what do you think?
